### PR TITLE
Redux integration - loading seats information from external source.

### PR DESCRIPTION
**Pull request by zergov**
Integrate redux in the application.

[Redux](https://github.com/reactjs/redux) is a library used to control the flow of the information inside an application. It is massively used with react applications. More information about this library and how it works here:
- http://redux.js.org/
- https://egghead.io/courses/getting-started-with-redux   <-- Super good videos by the writer of redux. 

This PR does the following: 
- add an action to load seats from an external source.
- reducer can handle this action
- index.js simulates the loading of seats using mocks
- Floorplan component render the seats via the state of the redux store.

### CODE REVIEW

**Comment by zergov** [comment]
@aviau ready for review

**Comment by ppot** [comment]
@zergov I will open my private F_.js project so you can take the JSON list of all seats.js that I have.

**Comment by zergov** [comment]
@ppot thanks dude

**Comment by ppot** [comment]
Also. I don't know what you're using. But i'm using http://www.createjs.com/easeljs as a canvas library.

**Comment by zergov** [comment]
Cool, i am using [paperjs](http://paperjs.org/) as the canvas library.

**Comment by ppot** [comment]
Yeah. I found Create.js better. Better layer management and also faster redrawing.

**Comment by ppot** [comment]
Also, it would be a good Idea to use https://github.com/rtfeldman/seamless-immutable with redux.

**Comment by zergov** [comment]
Eventually I want to [Immutable.js](https://facebook.github.io/immutable-js/). For this Pr tho, the reducer is super simple and pure, it does not really matter yet.

**Pull request merged**
